/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace OGP.Server
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ServerDefinition : TBase
  {
    private List<string> _SupportedGames;
    private int _TickDuration;
    private int _NumPlayers;

    public List<string> SupportedGames
    {
      get
      {
        return _SupportedGames;
      }
      set
      {
        __isset.SupportedGames = true;
        this._SupportedGames = value;
      }
    }

    public int TickDuration
    {
      get
      {
        return _TickDuration;
      }
      set
      {
        __isset.TickDuration = true;
        this._TickDuration = value;
      }
    }

    public int NumPlayers
    {
      get
      {
        return _NumPlayers;
      }
      set
      {
        __isset.NumPlayers = true;
        this._NumPlayers = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool SupportedGames;
      public bool TickDuration;
      public bool NumPlayers;
    }

    public ServerDefinition() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                SupportedGames = new List<string>();
                TList _list0 = iprot.ReadListBegin();
                for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                {
                  string _elem2 = null;
                  _elem2 = iprot.ReadString();
                  SupportedGames.Add(_elem2);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              TickDuration = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              NumPlayers = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ServerDefinition");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (SupportedGames != null && __isset.SupportedGames) {
        field.Name = "SupportedGames";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.String, SupportedGames.Count));
          foreach (string _iter3 in SupportedGames)
          {
            oprot.WriteString(_iter3);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (__isset.TickDuration) {
        field.Name = "TickDuration";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(TickDuration);
        oprot.WriteFieldEnd();
      }
      if (__isset.NumPlayers) {
        field.Name = "NumPlayers";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(NumPlayers);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ServerDefinition(");
      sb.Append("SupportedGames: ");
      sb.Append(SupportedGames);
      sb.Append(",TickDuration: ");
      sb.Append(TickDuration);
      sb.Append(",NumPlayers: ");
      sb.Append(NumPlayers);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
